theme: jekyll-theme-cayman

<body>
    <section class="page-header">
      <h1 class="project-name">Molecular Anthropology Group</h1>
      <h2 class="project-tagline">Genomics Training Module</h2>
    </section>
